baseURL = "https://collinsherman.github.io/"
languageCode = "en-us"
title = "Collin Sherman, Computer Science student at Washington and Lee University"
theme = ""

# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"

[menu]

# Main menu

[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    name = "Portfolio"
    url  = "/portfolio/"
    weight = 2

[[menu.main]]
    name = "About Me"
    url  = "/about/"
    weight = 3

[params]
    author = "CollinSherman"
    defaultKeywords = ["collin", "sherman"]
    defaultDescription = "Personal site for Collin Sherman"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "turquoise"

    about_me = "<p>Junior Computer Science student at Washington and Lee University.</p>"
    copyright = "&copy 2018 Collin Sherman"

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"
