baseURL = "https://collinsherman.github.io"
languageCode = "en-us"
title = "Personal Site for Collin Sherman, Computer Science student at Washington and Lee University"
theme = "hugo-universal-theme"
